### ISSUE TITLE
Data too long for column 'plugin_name'

### ISSUE THREAD

**Issue by 0v3rl04d** [hammackj/risu#107]
A nessus 'plug-in name' cause this error during the parsing of nessus file.

This is the output of risu:

`[!] Mysql2::Error: Data too long for column 'plugin_name' at row 1: UPDATE `individual_plugin_selections` SET `plugin_id` = 45498, `plugin_name` = 'SuSE 10 Security Update : MozillaFirefox, MozillaFirefox-branding-upstream, MozillaFirefox-translations, mozilla-xulrunner191, mozilla-xulrunner191-devel, mozilla-xulrunner191-gnomevfs, mozilla-xulrunner191-translations, python-xpcom191 (ZYPP Patch Number 6970)', `family` = 'SuSE Local Security Checks', `status` = 'enabled' WHERE `individual_plugin_selections`.`id` = 4436`

**Comment by hammackj** [comment]
Thanks, will get a release pushed out for this.
